name: 部署到腾讯云服务器

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      confirmation:
        description: '确认部署'
        required: true
        default: 'yes'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 部署到腾讯云服务器
        uses: appleboy/ssh-action@master
        with:
          host: 49.235.80.118
          username: root
          password: ${{ secrets.TENCENT_SSH_PASSWORD }}
          script: |
            # 创建项目目录（如果不存在）
            mkdir -p /var/www/love-home
            
            # 如果是首次部署，克隆仓库
            if [ ! -d "/var/www/love-home/.git" ]; then
              cd /var/www
              git clone https://github.com/${{ github.repository }}.git love-home
              cd love-home
            else
              # 如果已经存在，拉取最新代码
              cd /var/www/love-home
              git pull origin main
            fi
            
            # 安装依赖
            npm install
            
            # 重启或启动服务
            if command -v pm2 &> /dev/null; then
              pm2 restart server || pm2 start server.js
            else
              npm install -g pm2
              pm2 start server.js
            fi
            
            # 确保Nginx配置正确
            if [ -f "/var/www/love-home/nginx-config.conf" ]; then
              cp /var/www/love-home/nginx-config.conf /etc/nginx/sites-available/love-home.conf
              ln -sf /etc/nginx/sites-available/love-home.conf /etc/nginx/sites-enabled/
              
              # 测试并重载Nginx配置
              nginx -t && systemctl reload nginx
            fi
            
            echo "部署完成！"
      
      - name: 验证部署
        run: |
          # 等待服务启动
          sleep 10
          
          # 测试服务是否运行
          curl -I http://49.235.80.118/ || echo "HTTP 服务未响应，但部署可能已完成"
          echo "部署验证完成，请手动确认服务运行状态" 