name: 智慧社区平台自动部署

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 测试
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: 安装依赖
      run: npm ci
    
    - name: 运行测试
      run: npm test || echo "暂无测试，跳过"
  
  deploy:
    name: 部署到生产环境
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: 安装依赖
      run: npm ci
    
    - name: 构建前端
      run: |
        cd frontend-admin
        npm ci
        npm run build
    
    - name: 部署到服务器
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/love-home
          git pull
          npm ci
          cd frontend-admin
          npm ci
          npm run build
          cd ..
          pm2 reload ecosystem.config.js
    
    - name: 发送部署通知
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
        body: '{"text": "智慧社区平台已成功部署到生产环境！\n版本: ${{ github.sha }}\n提交者: ${{ github.actor }}\n提交信息: ${{ github.event.head_commit.message }}"}'

  notify_failure:
    name: 部署失败通知
    needs: [test, deploy]
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
    - name: 发送失败通知
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
        body: '{"text": "⚠️ 智慧社区平台部署失败！\n版本: ${{ github.sha }}\n提交者: ${{ github.actor }}\n提交信息: ${{ github.event.head_commit.message }}\n请检查GitHub Actions日志！"}' 